package com.example.coin.presentation

object SampleData {
    val coinListTest = listOf<TestInfoDataClass>(
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        )
        ,TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        )
        ,TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        )
        ,TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        )
        ,TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        )
        ,TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        ),
        TestInfoDataClass(
            "",
            "",
            "",
            ""
        )
        ,TestInfoDataClass(
            "",
            "",
            "",
            ""
        )

    )
}